### PR TITLE
return promise after backup

### PR DESCRIPTION
**Pull request by tyrsius**
currrently the backup promise returns after the first scan, continuing to do work after it has resolved.

### CODE REVIEW

**Comment by ninnemannk** [comment]
@shevchenkos - this would be awesome to get merged asap.

**Comment by shevchenkos** [comment]
Hi, guys.
I will have access to my PS in 3 hours.

**Comment by shevchenkos** [comment]
Package was merged and published

**Comment by ninnemannk** [comment]
Thanks!

**Pull request merged**
